config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank.rb
class Bank < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    @user = User.first
    @bank = Bank.first
    @game = GameEngine.new(@user, @bank).run
    render action: :index
  end

  def index
    @user = User.first
    @bank = Bank.first
    @game = GameEngine.new(@user, @bank).default
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<div class="container-fluid">
  <h1>Hello Player 1!</h1>
  <h2>Fruit machine</h2>
  <div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-1" style="background-color: <%= @game[:result][0] %>">
      @
    </div>
    <div class="col-md-1" style="background-color: <%= @game[:result][1] %>">
      @
    </div>
    <div class="col-md-1" style="background-color: <%= @game[:result][2] %>">
      @
    </div>
    <div class="col-md-1" style="background-color: <%= @game[:result][3] %>">
      @
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-3">
      <h3>Your account: <%= @user.account %></h3>
      <h3>Bank total: <%= @bank.total %></h3>
    </div>
  </div>
  <% if @game[:message] %>
    <h1><%= @game[:message] %></h1>
  <% end %>

  <%= button_to 'Play', games_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FruitMachine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>